// React/src/components/BlurbLinks.tsx
import Podcast from "../interfaces/podcast";
import style from './BlurbLinks.module.scss';
import Link from './Link';
import { FaApple } from "react-icons/fa";
import { FaRss } from "react-icons/fa";
import { FaLink } from "react-icons/fa";

interface Props {
    data: Podcast
}

const BlurbLinks:React.FC<Props> = ({data}) => {
    return (
        <div className={style.links}>
            <Link url={`https://podcasts.apple.com/us/podcast/alexa-stop-podcast/id${data.itunes_id}`} label="Itunes">
                <span className={style.linksIcon}>
                    <FaApple />
                </span>
            </Link>
            <Link url={data.website} label="Web">
                <span className={style.linksIcon}>
                    <FaLink />
                </span>
            </Link>
            <Link url={data.rss} label="RSS">
                <span className={style.linksIcon}>
                    <FaRss />
                </span>
            </Link>
        </div>
    )
}

export default BlurbLinks;

// Vue/src/components/BlurbLinks.vue

<script setup lang="ts">
    import Link from './Link.vue';
    import Podcast from '../interfaces/podcast';
    import { defineProps } from 'vue';

    defineProps<{ data: Podcast }>();
</script>

<template>
    <div class="links">
        <Link :url="`https://podcasts.apple.com/us/podcast/alexa-stop-podcast/id${data.itunes_id}`" label="Itunes" target="_blank">
            <fa-icon icon="fa-brands fa-apple" />
        </Link>
        <Link :url="data.website" label="Website" target="_blank">
            <fa-icon icon="fa-solid fa-link" />
        </Link>
        <Link :url="data.rss" label="RSS" target="_blank">
            <fa-icon icon="fa-solid fa-rss" />
        </Link>
    </div>
</template>

<style scoped lang="scss">
@import '../css/variables.scss';

.links {
    border-top: 1px solid $color-lightGray;
    margin-top: $spacing-md;
    padding-top: $spacing-sm;
    text-transform: uppercase;
}
</style>
