// React/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'
import data from './assets/data/podcasts-by-genre.json'
import Blurb from './components/Blurb';
import styles from './app.module.scss';
import Header from './components/Header';
import MorePodcasts from './components/MorePodcasts';

export const top5Pocasts = [
  data[1].podcasts[0],
  data[1].podcasts[9],
  data[1].podcasts[2],
  data[1].podcasts[8],
  data[1].podcasts[7],
];

function App() {
  const [showAll, setShowAll] = useState(false);

  const showMorePodcasts = () => {
    setShowAll(true);

    setTimeout(() => {
      const element = document?.getElementById('morePodcastContainer');
      const elementTop = element?.offsetTop || 0;
      const elementPlusWindow = elementTop;
      
      window.scrollTo({
        top: elementPlusWindow,
        left: 0,
        behavior: 'smooth',
      });
    }, 1);
  }

  return (
    <section className={styles.wrapper}>
      <Header data-testid="header" />
      <div className={styles.content}>
        {
          top5Pocasts.map((item, i) => (
            <Blurb data-testid={`blurb-${i}`} data={item} position={i+1} key={i} />
          ))
        }
        <button data-testid="findMoreButton" className={styles.showMoreButton} onClick={showMorePodcasts}>
          Find More Podcasts
        </button>
      </div>
      {showAll &&
        <MorePodcasts data-testid="morePodcasts" />
      }
    </section>
  )
}

export default App

// Vue/src/App.vue
<script setup lang="ts">
  import { reactive, ref } from 'vue';
  import data from './assets/data/podcasts-by-genre.json';
  import Header from './components/Header.vue';
  import Blurb from './components/Blurb.vue';
  import MorePodcasts from './components/MorePodcasts.vue';

  const podcasts = ref([
    data[1].podcasts[0],
    data[1].podcasts[9],
    data[1].podcasts[2],
    data[1].podcasts[8],
    data[1].podcasts[7],
  ]);

  const showMore = () => {
    state.showMorePodcasts = true;


    setTimeout(() => {
      const element = document?.getElementById('morePodcastContainer');
      const elementTop = element?.offsetTop || 0;
      const elementPlusWindow = elementTop;
      
      window.scrollTo({
        top: elementPlusWindow,
        left: 0,
        behavior: 'smooth',
      });
    }, 1);

  }

  const state = reactive({
    showMorePodcasts: false,
  });
</script>

<template>
  <section class="wrapper">
    <Header data-testid="header" />
    <div class="content">
      <div v-for="(item, i) in podcasts" :key="i">
        <Blurb :data-testid="`blurb-${i}`" :data="item" :position="i+1" />
      </div>
      <button data-testid="findMoreButton" class="showMoreButton" @click="showMore">
        Find More Podcasts
      </button>
    </div>
    <MorePodcasts id="morePodcastContainer" data-testid="morePodcasts" v-if="state.showMorePodcasts" :data="data" />
  </section>
</template>

<style scoped lang="scss">
  .wrapper {
      margin-top: 100vh;
      margin: 0;
      padding: 0;
  }
  .content {
      max-width: 730px;
      margin: 0 auto $spacing-lg;
      padding: 15px 30px 15px 15px;
  }
  .showMoreButton {
    cursor: pointer;
    padding: $spacing-sm $spacing-md;
    background-color: $color-lightPurple;
    color: $color-white;
    border: none;
    font-size: 16px;
    border-radius: 4px;
    letter-spacing: .05rem;
    text-transform: uppercase;
    box-shadow: 2px 2px 4px rgba($color: #000000, $alpha: 0.3);
    transition: all 0.5s;

    &:hover {
        background-color: $color-darkPurple;
        transition: all 0.5s;
    }
  }

</style>

<!-- These styles are unscoped, meaning they cascade as expected and impact the entire application -->
<style lang="scss">  
  @font-face {
    font-family: "SpaceMono";
    src: url('assets/fonts/SpaceMono-Regular.ttf');
    src: url('assets/fonts/SpaceMono-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: "SpaceMono";
    src: url('assets/fonts/SpaceMono-Bold.ttf');
    src: url('assets/fonts/SpaceMono-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
  }

  @font-face {
    font-family: "WorkSans";
    src: url('assets/fonts/WorkSans-Regular.ttf');
    src: url('assets/fonts/WorkSans-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  body {
    background-color: $color-offWhite;
    font-family: 'SpaceMono', Arial, Helvetica, sans-serif;
    margin: 0;
    min-width: 320px;
    min-height: 100vh;
    overflow-x: hidden;
  }

  a:link {
    text-decoration: none;
  }
</style>
